#!/usr/bin/env python3
"""Export a stable experience pack YAML (`experience.yaml`) with an update timestamp.

Why this exists
---------------
In the closed loop, we want a *single canonical* experience YAML file that:
- always has the same filename (`experience.yaml`) so other repos can depend on it
- carries a visible "last updated" timestamp for audit/debug
- remains compatible with both:
  - Youtu-Agent Hydra agent configs (so we can reuse it as an agent config if desired)
  - the debate/rank runtime `MAD/`, which loads YAML packs and extracts guideline
    blocks from `agent.instructions` lines like `[G0]. ...`

Inputs/Outputs
--------------
Input: a source agent YAML generated by Training-Free GRPO or debate update scripts, e.g.:
  configs/agents/practice/mad_full_..._agent.yaml

Output: a new YAML file with fixed naming, typically:
  configs/agents/practice/experience.yaml
and/or copied into:
  ../MAD/experience/experience.yaml
"""

from __future__ import annotations

import argparse
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml


def _repo_root() -> Path:
    # scripts/closed_loop/<this_file>.py -> scripts -> <repo_root>
    return Path(__file__).resolve().parents[2]


def _now_utc_iso() -> str:
    # Drop microseconds to make diffs stable.
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _load_yaml(path: Path) -> dict[str, Any]:
    obj = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(obj, dict):
        raise ValueError(f"Expected a YAML mapping at top-level, got {type(obj).__name__}")
    return obj


def _extract_instructions(raw: dict[str, Any]) -> str:
    agent = raw.get("agent")
    if not isinstance(agent, dict):
        raise ValueError("Missing top-level 'agent' mapping in source YAML.")
    instructions = agent.get("instructions")
    if not isinstance(instructions, str) or not instructions.strip():
        raise ValueError("Missing/empty 'agent.instructions' in source YAML.")
    return instructions


_GUIDELINE_START_RE = re.compile(r"^\s*\[(G\d+)\]\.\s*(.*)\s*$")


def _parse_guideline_blocks(instructions: str) -> list[str]:
    """Extract `[G*]. ...` guideline blocks from an instructions string.

    Returns:
        List of guideline texts with whitespace normalized to one line.
    """
    if not isinstance(instructions, str) or not instructions.strip():
        return []

    lines = instructions.splitlines()
    current: list[str] = []
    out: list[str] = []

    for line in lines:
        m = _GUIDELINE_START_RE.match(line)
        if m:
            if current:
                out.append(" ".join(current).strip())
            current = [m.group(2).strip()]
            continue

        if not current:
            continue
        cont = line.strip()
        if cont:
            current.append(cont)

    if current:
        out.append(" ".join(current).strip())

    # Normalize whitespace to keep each guideline single-line.
    return [" ".join(x.split()) for x in out if x and x.strip()]


def _guideline_title(text: str) -> str:
    if not text:
        return ""
    head = text.split(":", 1)[0].strip()
    return head.lower()


def _is_format_guideline(text: str) -> bool:
    """Heuristic filter: drop guidelines that are mostly about output formatting."""
    t = str(text or "").lower()
    title = _guideline_title(t)

    if not t.strip():
        return True

    # Hard format markers.
    if any(tok in t for tok in ("<think", "</think", "<answer", "</answer")):
        return True
    if "format compliance" in t:
        return True
    if title in {"tool-specific compliance", "tool specific compliance"}:
        return True
    if "no extraneous" in t:
        return True
    if "strict json" in t:
        return True
    if "json dict" in t and "keys" in t:
        return True
    if "key matching" in t and "metrics_to_predict" in t:
        return True

    return False


def _rewrite_guideline(text: str) -> str:
    """Optional rewrites to remove formatting language while keeping useful intent."""
    title = _guideline_title(text)
    if title in {"reasoning-output alignment", "reasoning-output consistency", "reasoning output alignment"}:
        return (
            "Consistency check: Ensure final numeric outputs align with evidence, unit conversions, metric definitions, "
            "and qualitative trends; avoid internal contradictions."
        )
    return str(text or "").strip()


def _build_chem_loop_instructions(guidelines: list[str]) -> str:
    header = (
        "You are a material-performance prediction assistant covering the registered 19 task directions.\n\n"
        "The user question contains an INPUT_JSON with:\n"
        "- material_name (required)\n"
        "- material_description and optional structured/custom material fields\n"
        "- task_type\n"
        "- metrics_to_predict (each item is either a metric key string, or an object {key, unit_hint})\n"
        "\n"
        "Output contract (evaluation-time):\n"
        "- Provide best-effort predictions for ALL requested metrics.\n"
        "- Values must be evaluable numbers; never output null/NaN.\n"
        "- Follow unit_hint if provided; otherwise normalize units by task_type.\n"
        "- Canonical units: conductivity S/m; photothermal_conversion_efficiency % numeric; "
        "thermal_conductivity W m-1 K-1; saturation_magnetization emu/g; neel_temperature K; "
        "minimum_concentration ppm; figure_of_merit dimensionless.\n"
        "- Never invent missing synthesis, structure, composition, element-content, or condition fields.\n"
        "- Treat A m2/kg as equivalent to emu/g for magnetic saturation magnetization.\n\n"
        "Helpful experiences (materials-focused):\n"
    )

    lines: list[str] = [header.rstrip()]
    for i, g in enumerate(guidelines):
        lines.append(f"[G{i}]. {g}")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description="Export a stable experience.yaml pack with updated_at_utc.")
    ap.add_argument(
        "--source_agent_yaml",
        type=str,
        required=True,
        help="Path to the source agent YAML (contains agent.instructions + [G*] blocks).",
    )
    ap.add_argument(
        "--output_yaml",
        type=str,
        default=str(_repo_root() / "configs" / "agents" / "practice" / "experience.yaml"),
        help="Path to write the stable experience.yaml (default: configs/agents/practice/experience.yaml).",
    )
    ap.add_argument(
        "--updated_at_utc",
        type=str,
        default=None,
        help="Optional override for updated_at_utc (ISO-8601). Default: now().",
    )
    ap.add_argument(
        "--normalize_chem_loop",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Normalize chem-loop packs: prune format-only guidelines and rewrite agent.instructions header (default: true).",
    )
    args = ap.parse_args()

    src_path = Path(args.source_agent_yaml)
    if not src_path.exists():
        raise SystemExit(f"Source agent YAML not found: {src_path}")

    out_path = Path(args.output_yaml)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    raw = _load_yaml(src_path)
    instructions = _extract_instructions(raw)
    if bool(args.normalize_chem_loop):
        parsed = _parse_guideline_blocks(instructions)
        kept = [_rewrite_guideline(g) for g in parsed if not _is_format_guideline(g)]
        # Also drop exact duplicates after rewrite/normalization.
        uniq: list[str] = []
        seen: set[str] = set()
        for g in kept:
            key = " ".join(str(g or "").split()).lower()
            if not key or key in seen:
                continue
            seen.add(key)
            uniq.append(" ".join(str(g).split()))
        instructions = _build_chem_loop_instructions(uniq)

    updated_at = str(args.updated_at_utc).strip() if args.updated_at_utc else _now_utc_iso()

    # Keep only the keys needed for either:
    # - loading as an AgentConfig in youtu-agent (type/model/agent/toolkits/env/max_turns)
    # - parsing as a Hydra-like pack in MAD ExperienceStore
    out_cfg: dict[str, Any] = {
        "updated_at_utc": updated_at,
        "source_agent_yaml": str(src_path),
    }
    for k in ("type", "model", "agent", "toolkits", "env", "max_turns"):
        if k in raw:
            out_cfg[k] = raw[k]

    # Ensure we preserve instructions (source may have been partially stripped upstream).
    out_cfg.setdefault("agent", {})
    if not isinstance(out_cfg["agent"], dict):
        out_cfg["agent"] = {}
    out_cfg["agent"]["instructions"] = instructions

    header = "# @package _global_\ndefaults:\n  - _self_\n\n"
    yaml_text = yaml.dump(out_cfg, default_flow_style=False, allow_unicode=True, sort_keys=False)
    out_path.write_text(header + yaml_text, encoding="utf-8")

    print(f"Wrote experience pack: {out_path}")
    print(f"updated_at_utc: {updated_at}")
    print(f"source_agent_yaml: {src_path}")


if __name__ == "__main__":
    main()
