from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _resolve_state_path(path_text: str, repo_root: Path) -> Path:
    path_text = str(path_text or "").strip()
    if not path_text:
        return Path("")
    path = Path(path_text)
    if path.is_absolute():
        return path
    if path_text.startswith("state/"):
        return repo_root / path_text
    return repo_root / path


def _read_csv(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        return list(reader.fieldnames or []), [dict(row) for row in reader]


def _write_csv(path: Path, headers: list[str], rows: list[dict[str, str]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key, "") for key in headers})


def _to_display_path(path: Path, repo_root: Path) -> str:
    try:
        return str(path.relative_to(repo_root))
    except Exception:
        return str(path)


def apply_fe_values(*, report_csv: Path, repo_root: Path) -> dict[str, Any]:
    _, report_rows = _read_csv(report_csv)
    updates_by_path: dict[Path, list[dict[str, str]]] = {}
    for row in report_rows:
        fe = str(row.get("faradaic_efficiency") or "").strip()
        if not fe:
            continue
        csv_path = _resolve_state_path(str(row.get("csv_path") or ""), repo_root)
        if not csv_path:
            continue
        updates_by_path.setdefault(csv_path, []).append(row)

    summary: list[dict[str, Any]] = []
    total_rows_applied = 0

    for csv_path, updates in sorted(updates_by_path.items(), key=lambda item: str(item[0])):
        if not csv_path.exists():
            summary.append(
                {
                    "csv_path": str(csv_path),
                    "applied_rows": 0,
                    "error": "csv_not_found",
                }
            )
            continue

        headers, rows = _read_csv(csv_path)
        backup_path = csv_path.with_suffix(csv_path.suffix + ".pre_apply_co2rr_fe_values.bak")
        if not backup_path.exists():
            backup_path.write_text(csv_path.read_text(encoding="utf-8-sig"), encoding="utf-8")

        applied_rows = 0
        for update in updates:
            try:
                csv_row_index = int(str(update.get("csv_row_index") or "").strip())
            except Exception:
                continue
            if csv_row_index < 2:
                continue
            row_pos = csv_row_index - 2
            if row_pos >= len(rows):
                continue
            row = rows[row_pos]
            row["faradaic_efficiency"] = str(update.get("faradaic_efficiency") or "").strip()
            unit = str(update.get("faradaic_efficiency_unit") or "").strip() or "%"
            row["faradaic_efficiency_unit"] = unit
            applied_rows += 1

        _write_csv(csv_path, headers, rows)
        total_rows_applied += applied_rows
        summary.append(
            {
                "csv_path": _to_display_path(csv_path, repo_root),
                "backup_path": _to_display_path(backup_path, repo_root),
                "applied_rows": applied_rows,
            }
        )

    summary_payload = {
        "report_csv": str(report_csv),
        "files_touched": len(summary),
        "rows_applied": total_rows_applied,
        "items": summary,
    }
    report_dir = report_csv.parent
    summary_path = report_dir / "co2rr_feedback_apply_fe_summary.json"
    try:
        summary_path.write_text(json.dumps(summary_payload, ensure_ascii=False, indent=2), encoding="utf-8")
    except PermissionError:
        summary_path = Path("/tmp/co2rr_feedback_apply_fe_summary.json")
        summary_path.write_text(json.dumps(summary_payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return {"summary_path": str(summary_path), **summary_payload}


def main() -> None:
    parser = argparse.ArgumentParser(description="Apply manually filled FE values back into historical CO2RR feedback CSVs.")
    parser.add_argument(
        "--report-csv",
        default="/state/reports/co2rr_feedback_missing_fe_rows.csv" if Path("/state").exists() else "state/reports/co2rr_feedback_missing_fe_rows.csv",
        help="CSV report generated by backfill_historical_co2rr_feedback_csv.py with faradaic_efficiency filled in.",
    )
    args = parser.parse_args()

    repo_root = _repo_root()
    report_csv = _resolve_state_path(args.report_csv, repo_root)
    result = apply_fe_values(report_csv=report_csv, repo_root=repo_root)
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
